name: Deploy to GKE via IAP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/19102981664/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-cicd@sound-chimera-464005-q1.iam.gserviceaccount.com"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/sound-chimera-464005-q1/k8-repo/hello-world:$GITHUB_SHA
          
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Get GKE credentials (IAP tunnel)
        run: |
          gcloud container clusters get-credentials k8-cluster \
            --region=us-central1 \
            --project=sound-chimera-464005-q1 \
            --internal-ip \
            --tunnel-through-iap

      - name: Deploy to GKE
        run: |
           kubectl set image deployment/hello-world-deployment hello-world=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/k8-repo/hello-world:${{ github.sha }}
           kubectl rollout status deployment/hello-world-deployment
